### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by alpapak** [b4dpxl/UPS-Plus-Daemon#1]
Hello,

Nice work. 

I would like to ask if you can create a daemonised version of the UPS Plus software with out rtc and mqtt. Simple ups with ac power on, safe shutdown and email when power off or shutdown. As it will be useful for home server, pi with upsplus. 

For email, msmtp.

Thank you in advance.

**Comment by b4dpxl** [comment]
This version already doesn't use the RTC as I have no use for it, and if you don't enable MQTT in the config it will work without it. Adding email on shutdown isn't of use to me, as if I have no power I have no Internet connection.
